spring.application.name=core
# PostgreSQL database configuration
# $env:DB_URL_CORE="jdbc:postgresql://localhost:5432/objectStore"

spring.datasource.url=${DB_URL_CORE}
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.session.jdbc.initialize-schema=always

logging.level.root=INFO
logging.level.com.parthakadam.space==DEBUG

# Maximum size for a single file (e.g., 50MB)
spring.servlet.multipart.max-file-size=50MB
# Maximum size for the entire request (e.g., 50MB)
spring.servlet.multipart.max-request-size=50MB



# Kafka 
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
