spring.application.name=auth_service
server.port=8081
# ################## temo TODO 
# PostgreSQL database configuration
# $env:DB_URL="jdbc:postgresql://localhost:5432/objectStore"

spring.datasource.url=jdbc:postgresql://localhost:5432/object_store_auth
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.session.jdbc.initialize-schema=always

# Flyway configurations
# spring.flyway.enabled=true
# spring.flyway.locations=classpath:db/migration

logging.level.root=INFO
logging.level.com.parthakadam.space==DEBUG

# Maximum size for a single file (e.g., 50MB)
spring.servlet.multipart.max-file-size=50MB
# Maximum size for the entire request (e.g., 50MB)
spring.servlet.multipart.max-request-size=50MB